version: "3.9"

services:
  app:
    image: fastapi-hello:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app
    env_file: [.env]
    profiles: ["dev"]

  app-prod:
    image: fastapi-hello:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    env_file: [.env]
    profiles: ["prod"]
