from typing import Optional
from app.domain.entities.token import ActivationToken


class TokenRepo:
    def upsert(self, user_id: int, code_hash: str) -> ActivationToken: ...
    def get_active_for_user(self, user_id: int) -> Optional[ActivationToken]: ...
    def consume(self, token_id: int) -> None: ...
