from typing import Optional
from app.domain.entities.user import User


class UserRepo:
    def create(self, email: str, password_hash: str) -> int: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def activate(self, user_id: int) -> bool: ...
